### ISSUE TITLE
Unable to connect to install correctly

### ISSUE THREAD

**Issue by aumarco** [dessalines/simple-vote#33]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simplevote 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ simplevote ---
[INFO] Deleting /home/hk/Desktop/simple-vote-master/service/target
[INFO] 
[INFO] --- properties-maven-plugin:1.0-alpha-2:write-project-properties (default) @ simplevote ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simplevote ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 27 resources
[INFO] 
[INFO] --- liquibase-maven-plugin:3.5.1:update (default) @ simplevote ---
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.806 s
[INFO] Finished at: 2017-12-19T14:59:32+08:00
[INFO] Final Memory: 13M/166M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.1:update (default) on project simplevote: Error setting up or running Liquibase: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "simplevote" -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I got to this stage and dont know what is wrong

**Comment by dessalines** [comment]
oops I think i have the creds wrong in the README, they should be:
user: `simplevote`
pass: `asdf`

So create a postgres user with that username and password.
