### ISSUE TITLE
Some other warning and error

### ISSUE THREAD

**Issue by aumarco** [dessalines/simple-vote#34]
Excluding it from installation.
[3/4] Linking dependencies...
warning " > angular2-jwt@0.2.3" has incorrect peer dependency "@angular/core@^2.0.0||^4.0.0".
warning " > angular2-jwt@0.2.3" has incorrect peer dependency "@angular/http@^2.0.0||^4.0.0".
warning " > codelyzer@2.0.1" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning " > codelyzer@2.0.1" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".

cssWarning: Can't resolve all parameters for NG2WebSocket in /home/hk/simple-vote/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for NG2WebSocket in /home/hk/simple-vote/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x

**Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
nohup: redirecting stderr to stdout**

**Comment by dessalines** [comment]
Very first google result shows that its a maven issue. 

https://stackoverflow.com/questions/11118237/maven-error-could-not-find-or-load-main-class-org-codehaus-plexus-classworlds-l
