### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by deamons** [dessalines/simple-vote#36]
Hello there, thanks for your afford making this software possible.
I have to install the simple-vote software on a windows environment, but the installation is challenging. I´m currently following the steps of the install_prod.sh but I`m failing to build the project in maven. Maybe it would be better also for other guys who want to run this on Windows to provide a binary version for windows?

**Comment by dessalines** [comment]
Its probably a problem with your maven configuration in windows, but I have no idea what the problem is until you post the stacktrace.

**Comment by dessalines** [comment]
And secondly I'd suggest reading the `readme` again, you should be using `./install_dev.sh` for local installations. I doubt your running a production windows environment.

**Comment by dessalines** [comment]
I'll close this until you have another problem.
