### ISSUE TITLE
Self hosted Install help

### ISSUE THREAD

**Issue by dsrukmana** [dessalines/simple-vote#48]
Can someone help me out, I'm trying to install on Ubuntu vps I already follow as per guide but at the end I can't found /Config directory for edit host production.

**Comment by dessalines** [comment]
Can you be more specific? What's the error you're getting?

**Comment by dessalines** [comment]
Oops my bad, I found the place, and fixed it. 

For a production environment, edit `ui/src/environments/environment.prod.ts` to point to your hostname, then run:
