### ISSUE TITLE
Alternative requirements?

### ISSUE THREAD

**Issue by petrk94** [dessalines/simple-vote#63]
Hello,

I really like the Web App and want to self host it on my shared host server, BUT this requirements are only available on root server.
Java I can not run on shared host and Postgres? This should be optional, I can use MySQL, MariaDB and worst case even MongoDB, but Postgres I can not use :( 
Exist a alternative or further development?

Thanks

**Comment by dessalines** [comment]
Sorry, this uses postgres only. You're free to fork this and make a mysql version if you like.

**Comment by petrk94** [comment]
I dont know how its connected to your app. 
In theory I would just replace the settings with the mysql data, but due I have no knowledge about postgres, I dont know how to make it :/

**Comment by dessalines** [comment]
I suggest hosting on a server that you control, and installing postgres on it.
