### ISSUE TITLE
FR: Snap install

### ISSUE THREAD

**Issue by gerroon** [dessalines/simple-vote#66]
Hi

It would be nice if there is a Snap package for this app. 

thanks

**Comment by dessalines** [comment]
Its not really a user application, but a server one, so docker is more appropriate, since this needs a postgres server, and java. I'm happy to accept PRs, but afaik snap packages are only for user apps.

**Comment by gerroon** [comment]
Actually, maybe not. Check out Wekan, it provides  Snap app and works great.
