### ISSUE TITLE
Dcoker build FE-to-BE connection issue

### ISSUE THREAD

**Issue by zhostasa** [dessalines/simple-vote#73]
After the latest Docker COPY fix I ran into yet another issue. I ran fresh deployment of the master branch, but when attempting to login or sign up the frontend seems to be unable to call backend, specifically I get this error: 

POST http://localhost:4567/login net::ERR_CONNECTION_REFUSED

followed by:

TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_6__.Observable.throw is not a function

you can observe it yourself at http://194.182.72.244:4567/#/

You are of course welcome to check it out at the machine, the credentials remain the same.

Please help, I would try to figure it myself, but Angular is not really my thing.

**Comment by dessalines** [comment]
You need to change your env endpoint : https://github.com/dessalines/simple-vote#start-the-docker-instance

**Comment by zhostasa** [comment]
I of course attempted that, same result. It did seem weird that the error message seems to say localhost regardless, but again, frontend, not my thing

**Comment by dessalines** [comment]
I'm testing this now

**Comment by dessalines** [comment]
Okay, all is working now. http://194.182.72.244:4567

Take a look at your dockerfile to see the changes it made.

**Comment by dessalines** [comment]
Okay, all is working now. http://194.182.72.244:4567

Take a look at your dockerfile to see the changes it made.
