### ISSUE TITLE
Approval voting is a little.. weirdly implemented

### ISSUE THREAD

**Issue by Skrylar** [dessalines/simple-vote#75]
Approval voting seems to be implemented as range voting with 0, 10 or abstain options. This leads to some weirdness:

- Applesauce has 2 :+1: 
- Cranberry has 1 :+1:

The UI then reports that both have a score of 10.

Under approval voting, shouldn't Applesauce have a higher score than Cranberry? The system intends to reward the candidate with the most general approval, but it's actually saying that a candidate with *less* approval is *equal* to one with *more*. :confused:

**Comment by dessalines** [comment]
The scores aren't sums, but averages. Every option has a vote count, and a value ( in this case, none, 0 or 10).

As for when there are no downvotes, its a sorting issue that I have to fix, these are incorrectly sorted : ![](https://i.imgur.com/CjjC2Zy.png)
