### ISSUE TITLE
Pointing poker style votes show up as range votes temporarily

### ISSUE THREAD

**Issue by Skrylar** [dessalines/simple-vote#76]
With a regular browser and private browser tab open (to simulate two users), one can see that adding a new pointing poker style vote seems to synchronize to other users as a new range vote being added. Refreshing the page _does_ change it to the correct voting type.

**Comment by dessalines** [comment]
Just verified this, thanks! I'll try to figure out what's going on.

**Comment by dessalines** [comment]
This appears to be the type not switching.
