### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Restioson** [dessalines/simple-vote#77]
Appears to be broken. Or perhaps down? ![image](https://user-images.githubusercontent.com/6688948/67966748-147cac00-fc0d-11e9-901e-6861887a0220.png)

**Comment by dessalines** [comment]
Oops, sorry about that. I fixed and brought it back up. Was a server restart for some reason, my bad.

**Comment by filip-v** [comment]
502 error again

**Comment by dessalines** [comment]
Sry about that, I fixed, and I also added it to the server restart crontab.
